name: My_BMI
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0
  flutter_launcher_icons: ^0.7.5
  animated_splash: ^1.0.0
  flutter_statusbarcolor: ^0.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: AvenirLTStd
      fonts:
        - asset: fonts/AvenirLTStd-Book.otf